name: Compilar y Publicar Electron

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Compilar en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # 1. Instalar pnpm de forma global en la máquina virtual
      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # O la versión específica de pnpm que uses localmente

      # 2. Configurar Node.js enlazándolo con el caché de pnpm
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm' # Ahora GitHub Actions buscará correctamente tu archivo pnpm-lock.yaml

      # 3. Instalar dependencias usando pnpm en modo estricto de CI
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Compilar y empaquetar aplicación
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
