name: Compilar y Publicar Electron

# El proceso se activará solo cuando subas una etiqueta (tag) que empiece con "v" (ej: v1.0.0)
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Compilar en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    # Matriz para compilar en los 3 sistemas operativos en paralelo
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # 1. Copia el código de tu repositorio en la máquina virtual de GitHub
      - name: Descargar código
        uses: actions/checkout@v4

      # 2. Instala Node.js (puedes cambiar el 22 por la versión que uses)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 3. Instala las dependencias de tu proyecto (Node modules)
      - name: Instalar dependencias
        run: npm ci

      # 4. Compila la app y crea la Release en GitHub de forma automática
      - name: Compilar y empaquetar aplicación
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
